export type MockVisit = {
  id: string
  cleanerName: string
  siteName: string
  dayOfWeek: number
  startTime: string
  endTime: string
  color?: string
}

const buildMockSchedules = (): MockVisit[] => {
  return [
    {
      id: 'visit-psm-marine-mosleen-mon',
      cleanerName: 'Mosleen',
      siteName: 'PSM Marine',
      dayOfWeek: 1,
      startTime: '18:00',
      endTime: '21:00',
      color: '#0F60FF',
    },
    {
      id: 'visit-psm-marine-mosleen-wed',
      cleanerName: 'Mosleen',
      siteName: 'PSM Marine',
      dayOfWeek: 3,
      startTime: '18:00',
      endTime: '21:00',
      color: '#2563EB',
    },
    {
      id: 'visit-psm-marine-mosleen-fri',
      cleanerName: 'Mosleen',
      siteName: 'PSM Marine',
      dayOfWeek: 5,
      startTime: '18:00',
      endTime: '21:00',
      color: '#1E3A8A',
    },
    {
      id: 'visit-adams-gill-everyday',
      cleanerName: "Gill",
      siteName: "Adam's",
      dayOfWeek: 0,
      startTime: '10:30',
      endTime: '19:30',
      color: '#EA580C',
    },
    {
      id: 'visit-adams-gill-mon',
      cleanerName: "Gill",
      siteName: "Adam's",
      dayOfWeek: 1,
      startTime: '10:30',
      endTime: '19:30',
      color: '#EA580C',
    },
    {
      id: 'visit-adams-gill-tue',
      cleanerName: "Gill",
      siteName: "Adam's",
      dayOfWeek: 2,
      startTime: '10:30',
      endTime: '19:30',
      color: '#EA580C',
    },
    {
      id: 'visit-adams-gill-wed',
      cleanerName: "Gill",
      siteName: "Adam's",
      dayOfWeek: 3,
      startTime: '10:30',
      endTime: '19:30',
      color: '#EA580C',
    },
    {
      id: 'visit-adams-gill-thu',
      cleanerName: "Gill",
      siteName: "Adam's",
      dayOfWeek: 4,
      startTime: '10:30',
      endTime: '19:30',
      color: '#EA580C',
    },
    {
      id: 'visit-adams-gill-fri',
      cleanerName: "Gill",
      siteName: "Adam's",
      dayOfWeek: 5,
      startTime: '10:30',
      endTime: '19:30',
      color: '#EA580C',
    },
    {
      id: 'visit-adams-gill-sat',
      cleanerName: "Gill",
      siteName: "Adam's",
      dayOfWeek: 6,
      startTime: '10:30',
      endTime: '19:30',
      color: '#EA580C',
    },
    {
      id: 'visit-rdp-sienna-fri',
      cleanerName: 'Sienna',
      siteName: 'RDP',
      dayOfWeek: 5,
      startTime: '15:00',
      endTime: '19:00',
      color: '#10B981',
    },
    {
      id: 'visit-general-harry-daily-sun',
      cleanerName: 'Harry Newton',
      siteName: 'General',
      dayOfWeek: 0,
      startTime: '09:00',
      endTime: '17:00',
      color: '#8B5CF6',
    },
    {
      id: 'visit-general-harry-daily-mon',
      cleanerName: 'Harry Newton',
      siteName: 'General',
      dayOfWeek: 1,
      startTime: '09:00',
      endTime: '17:00',
      color: '#8B5CF6',
    },
    {
      id: 'visit-general-harry-daily-tue',
      cleanerName: 'Harry Newton',
      siteName: 'General',
      dayOfWeek: 2,
      startTime: '09:00',
      endTime: '17:00',
      color: '#8B5CF6',
    },
    {
      id: 'visit-general-harry-daily-wed',
      cleanerName: 'Harry Newton',
      siteName: 'General',
      dayOfWeek: 3,
      startTime: '09:00',
      endTime: '17:00',
      color: '#8B5CF6',
    },
    {
      id: 'visit-general-harry-daily-thu',
      cleanerName: 'Harry Newton',
      siteName: 'General',
      dayOfWeek: 4,
      startTime: '09:00',
      endTime: '17:00',
      color: '#8B5CF6',
    },
    {
      id: 'visit-general-harry-daily-fri',
      cleanerName: 'Harry Newton',
      siteName: 'General',
      dayOfWeek: 5,
      startTime: '09:00',
      endTime: '17:00',
      color: '#8B5CF6',
    },
    {
      id: 'visit-general-harry-daily-sat',
      cleanerName: 'Harry Newton',
      siteName: 'General',
      dayOfWeek: 6,
      startTime: '09:00',
      endTime: '17:00',
      color: '#8B5CF6',
    },
    {
      id: 'visit-general-jackie-daily-sun',
      cleanerName: 'Jackie Palmer',
      siteName: 'General',
      dayOfWeek: 0,
      startTime: '18:00',
      endTime: '22:00',
      color: '#F97316',
    },
    {
      id: 'visit-general-jackie-daily-mon',
      cleanerName: 'Jackie Palmer',
      siteName: 'General',
      dayOfWeek: 1,
      startTime: '18:00',
      endTime: '22:00',
      color: '#F97316',
    },
    {
      id: 'visit-general-jackie-daily-tue',
      cleanerName: 'Jackie Palmer',
      siteName: 'General',
      dayOfWeek: 2,
      startTime: '18:00',
      endTime: '22:00',
      color: '#F97316',
    },
    {
      id: 'visit-general-jackie-daily-wed',
      cleanerName: 'Jackie Palmer',
      siteName: 'General',
      dayOfWeek: 3,
      startTime: '18:00',
      endTime: '22:00',
      color: '#F97316',
    },
    {
      id: 'visit-general-jackie-daily-thu',
      cleanerName: 'Jackie Palmer',
      siteName: 'General',
      dayOfWeek: 4,
      startTime: '18:00',
      endTime: '22:00',
      color: '#F97316',
    },
    {
      id: 'visit-general-jackie-daily-fri',
      cleanerName: 'Jackie Palmer',
      siteName: 'General',
      dayOfWeek: 5,
      startTime: '18:00',
      endTime: '22:00',
      color: '#F97316',
    },
    {
      id: 'visit-general-jackie-daily-sat',
      cleanerName: 'Jackie Palmer',
      siteName: 'General',
      dayOfWeek: 6,
      startTime: '18:00',
      endTime: '22:00',
      color: '#F97316',
    },
  ]
}

export const MOCK_VISITS: MockVisit[] = buildMockSchedules()

export const getMockVisitsForWeek = (): MockVisit[] => {
  return MOCK_VISITS
}


